# Stage 10: the kind cluster. First in the graph, depends on nothing.

include "root" {
  path = find_in_parent_folders("root.hcl")
}

terraform {
  # The existing stage, unchanged. Terragrunt copies it into .terragrunt-cache
  # and runs Terraform there with the backend generated by root.hcl.
  source = "../../terraform/10-cluster"
}

# Inputs become TF_VAR_* environment variables. The stage's defaults already
# match the other runbooks, so nothing is overridden here. Uncomment to change
# a value for every run without editing the stage or typing -var.
# inputs = {
#   gateway_host_port = 18080
# }
