// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entries (wallet_id, transfer_id, direction, amount, balance_after)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, wallet_id, transfer_id, direction, amount, balance_after, created_at
`

type CreateLedgerEntryParams struct {
	WalletID     pgtype.UUID
	TransferID   pgtype.UUID
	Direction    string
	Amount       int64
	BalanceAfter int64
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.WalletID,
		arg.TransferID,
		arg.Direction,
		arg.Amount,
		arg.BalanceAfter,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TransferID,
		&i.Direction,
		&i.Amount,
		&i.BalanceAfter,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerEntries = `-- name: ListLedgerEntries :many
SELECT id, wallet_id, transfer_id, direction, amount, balance_after, created_at
FROM ledger_entries
WHERE wallet_id = $1
  AND (
    $3::timestamptz IS NULL
    OR (created_at, id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListLedgerEntriesParams struct {
	WalletID        pgtype.UUID
	Limit           int32
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
}

func (q *Queries) ListLedgerEntries(ctx context.Context, arg ListLedgerEntriesParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntries,
		arg.WalletID,
		arg.Limit,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TransferID,
			&i.Direction,
			&i.Amount,
			&i.BalanceAfter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
