// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimUnpublishedOutboxEvents = `-- name: ClaimUnpublishedOutboxEvents :many
WITH claimed AS (
  SELECT id
  FROM outbox_events
  WHERE published_at IS NULL
  ORDER BY created_at, id
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
UPDATE outbox_events AS outbox
SET claimed_at = now()
FROM claimed
WHERE outbox.id = claimed.id
RETURNING outbox.id, outbox.topic, outbox.partition_key, outbox.payload, outbox.claimed_at, outbox.published_at, outbox.created_at
`

func (q *Queries) ClaimUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimUnpublishedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.PartitionKey,
			&i.Payload,
			&i.ClaimedAt,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (topic, partition_key, payload)
VALUES ($1, $2, $3)
RETURNING id, topic, partition_key, payload, claimed_at, published_at, created_at
`

type CreateOutboxEventParams struct {
	Topic        string
	PartitionKey string
	Payload      []byte
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent, arg.Topic, arg.PartitionKey, arg.Payload)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.PartitionKey,
		&i.Payload,
		&i.ClaimedAt,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events
SET published_at = now()
WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}
