// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saga_wallet_operations.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSagaWalletOperation = `-- name: CreateSagaWalletOperation :one
INSERT INTO saga_wallet_operations (
  payment_id,
  operation,
  idempotency_key,
  wallet_id,
  amount_cents,
  currency,
  status,
  balance_after_cents
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, payment_id, operation, idempotency_key, wallet_id, amount_cents, currency, status, balance_after_cents, created_at, updated_at
`

type CreateSagaWalletOperationParams struct {
	PaymentID         pgtype.UUID
	Operation         string
	IdempotencyKey    string
	WalletID          pgtype.UUID
	AmountCents       int64
	Currency          string
	Status            string
	BalanceAfterCents int64
}

func (q *Queries) CreateSagaWalletOperation(ctx context.Context, arg CreateSagaWalletOperationParams) (SagaWalletOperation, error) {
	row := q.db.QueryRow(ctx, createSagaWalletOperation,
		arg.PaymentID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.WalletID,
		arg.AmountCents,
		arg.Currency,
		arg.Status,
		arg.BalanceAfterCents,
	)
	var i SagaWalletOperation
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.WalletID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.BalanceAfterCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSagaWalletOperation = `-- name: GetSagaWalletOperation :one
SELECT id, payment_id, operation, idempotency_key, wallet_id, amount_cents, currency, status, balance_after_cents, created_at, updated_at
FROM saga_wallet_operations
WHERE payment_id = $1 AND operation = $2
`

type GetSagaWalletOperationParams struct {
	PaymentID pgtype.UUID
	Operation string
}

func (q *Queries) GetSagaWalletOperation(ctx context.Context, arg GetSagaWalletOperationParams) (SagaWalletOperation, error) {
	row := q.db.QueryRow(ctx, getSagaWalletOperation, arg.PaymentID, arg.Operation)
	var i SagaWalletOperation
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.WalletID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.BalanceAfterCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSagaWalletOperationForUpdate = `-- name: GetSagaWalletOperationForUpdate :one
SELECT id, payment_id, operation, idempotency_key, wallet_id, amount_cents, currency, status, balance_after_cents, created_at, updated_at
FROM saga_wallet_operations
WHERE payment_id = $1 AND operation = $2
FOR UPDATE
`

type GetSagaWalletOperationForUpdateParams struct {
	PaymentID pgtype.UUID
	Operation string
}

func (q *Queries) GetSagaWalletOperationForUpdate(ctx context.Context, arg GetSagaWalletOperationForUpdateParams) (SagaWalletOperation, error) {
	row := q.db.QueryRow(ctx, getSagaWalletOperationForUpdate, arg.PaymentID, arg.Operation)
	var i SagaWalletOperation
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.WalletID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.BalanceAfterCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockWalletForUpdate = `-- name: LockWalletForUpdate :one
SELECT id, user_id, balance, currency, created_at, updated_at
FROM wallets
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockWalletForUpdate(ctx context.Context, id pgtype.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, lockWalletForUpdate, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
