// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfers.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (from_wallet_id, to_wallet_id, amount)
VALUES ($1, $2, $3)
RETURNING id, from_wallet_id, to_wallet_id, amount, status, created_at
`

type CreateTransferParams struct {
	FromWalletID pgtype.UUID
	ToWalletID   pgtype.UUID
	Amount       int64
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer, arg.FromWalletID, arg.ToWalletID, arg.Amount)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromWalletID,
		&i.ToWalletID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
