ALTER TABLE sagas
  ADD COLUMN IF NOT EXISTS fraud_session_id TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS fraud_action TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS fraud_risk_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fraud_reason TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS fraud_flagged_at TIMESTAMPTZ NOT NULL DEFAULT '0001-01-01 00:00:00+00',
  ADD COLUMN IF NOT EXISTS deferred_payment_json TEXT NOT NULL DEFAULT '';
