ALTER TABLE sagas
  ADD COLUMN IF NOT EXISTS fraud_session_id TEXT,
  ADD COLUMN IF NOT EXISTS fraud_action TEXT,
  ADD COLUMN IF NOT EXISTS fraud_risk_score DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS fraud_reason TEXT,
  ADD COLUMN IF NOT EXISTS fraud_flagged_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS deferred_payment_json TEXT;
